export enum HorseRaceGameMutationTypes {
  SET_HORSES = "SET_HORSES",
  SET_ROUNDS = "SET_ROUNDS",
  SET_STATUS = "SET_STATUS",
  SET_CURRENT_ROUND = "SET_CURRENT_ROUND",
  PUSH_RESULT = "PUSH_RESULT",
  RESET_RESULTS = "RESET_RESULTS",
  UPDATE_CURRENT_ROUND = "UPDATE_CURRENT_ROUND",
}